id: opecha:P004239
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19042
  title: བོད་ཀྱི་རི་མོའི་སྒྱུ་རྩལ་ལས་ལྷ་སྐུའི་ཐིག་རྩ་དང་ཤིང་ཚོན་སོགས་ཀྱི་རྨང་གཞིའི་ཤེས་བྱ་འགྲོ་ཕན་བློ་གསར་དགའ་སྐྱེད།
  volume: ''
  author: ''
